version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/usr/share/nginx/html
    links:
      - nodejs
  nodejs:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    command: /bin/bash -c "npm install &&  npm start"
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=reax
      - MYSQL_PASSWORD=46197115
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

          