version: '3'
services:
  react:
    container_name: react_container
    image: node:latest
    working_dir: /react
    volumes:
      - ./react:/react
    command: /bin/bash -c "npm install && npm run build"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./react/build:/usr/share/nginx/web
    links:
      - nodejs
    depends_on:
      - react

  nodejs:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    command: /bin/bash -c "npm install && npm start"
    depends_on:
      - mariadb
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=reax
      - MYSQL_PASSWORD=46197115
    # ports:
    #   - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
  
  php:
    image: php:fpm-alpine
    links:
      - nginx
      
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

          